version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
      target: base
    container_name: leek-nginx
    command: [nginx-debug, '-g', 'daemon off;']
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - backend
    networks:
      - leek-network

  client:
    build:
      context: ./client
      target: base
    container_name: leek-client
    command: yarn start
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/app/src
    networks:
      - leek-network

  backend:
    build:
      context: ./backend
      target: base
    container_name: leek-backend
    command: yarn start:dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    ports:
      - 3001:3001
    networks:
      - leek-network
  # user:
  #   build:
  #     context: ./user
  #     dockerfile: Dockerfile
  #     target: base
  #   container_name: szp-user
  #   restart: unless-stopped
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./user/src:/usr/src/app/src
  #   networks:
  #     - zaloopets-network

  # mongo:
  #   build: ./mongo/dockerFolder
  #   container_name: szp-mongo
  #   volumes:
  #     - ./mongo/data:/data/db
  #   networks:
  #     - zaloopets-network

networks:
  leek-network:
    driver: bridge
