version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: base
    container_name: szp-nginx
    command: [nginx-debug, '-g', 'daemon off;']
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user
      - client
    networks:
      - zaloopets-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: base
    container_name: szp-client
    command: yarn start
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      WDS_SOCKET_PORT: 0
    volumes:
      - ./client/src:/usr/src/app/src
    networks:
      - zaloopets-network

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
      target: base
    container_name: szp-user
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - ./user/src:/usr/src/app/src
    networks:
      - zaloopets-network

  mongo:
    build: ./mongo/dockerFolder
    container_name: szp-mongo
    volumes:
      - ./mongo/data:/data/db
    networks:
      - zaloopets-network

networks:
  zaloopets-network:
    driver: bridge
